### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by ap2322** [Wyattwicks/mod_0_skills#1]
Wyatt, you performed well enough on the assessment to merit a chance to make some changes that can promote you to `technical ready`. Please make the following updates by noon MST Saturday:

- [x] Try running each line of code from `variables.txt` in your terminal using irb. Check that your variables are updating correctly by calling the variable name after you modify it. Correct any errors you come across and update your `variables.txt`.
- [ ] Class names should be PascalCase. Update your class 2 name to reflect this convention.

**Comment by Wyattwicks** [comment]
Hello Alice, I have made the necessary changes. For the first issue I corrected my variable assignments, I think I was reading too far in to what was being asked and got confused. As I can not see the assessment questions I'm pretty sure I updated everything to match what the assessment asked, but if there is a way to review the assessment requirements I could make sure I did everything needed for that part. Please let me know if there is anything else I need to do, thanks!

**Comment by ap2322** [comment]
Good work with these updates Wyatt, you're officially `technical ready`. 
- Good job and keep following Ruby conventions around naming classes (PascalCase, singular), attributes and methods (snake_case), and making your attribute and method names descriptive & brief.
- Good work conceptualizing of a class as an overall blueprint and the object/instance as a single example of that class.
Very nice attribute/method interaction with all methods using or modifying attributes. 
- Good work updating your Ruby syntax in variables.txt to run.
